import { Merchant } from '../models/Mecrhant.model';

export const merchantArray: Merchant[] = [
  {
    id: 1,
    imgs: 'fa fa-home',
    companyTitle: 'Company A',
    totalVouchers: 100,
    totalUsedVouchers: 60,
    totalUnusedVouchers: 40,
    pendingCommission: 500,
    paidCommission: 300,
  },
  {
    id: 2,
    imgs: 'fa fa-car',
    companyTitle: 'Company B',
    totalVouchers: 150,
    totalUsedVouchers: 90,
    totalUnusedVouchers: 60,
    pendingCommission: 700,
    paidCommission: 500,
  },
  {
    id: 3,
    imgs: 'fa fa-shopping-cart',
    companyTitle: 'Company C',
    totalVouchers: 200,
    totalUsedVouchers: 150,
    totalUnusedVouchers: 50,
    pendingCommission: 900,
    paidCommission: 700,
  },
  {
    id: 4,
    imgs: 'fa fa-coffee',
    companyTitle: 'Company D',
    totalVouchers: 120,
    totalUsedVouchers: 80,
    totalUnusedVouchers: 40,
    pendingCommission: 600,
    paidCommission: 400,
  },
  {
    id: 5,
    imgs: 'fa fa-tree',
    companyTitle: 'Company E',
    totalVouchers: 180,
    totalUsedVouchers: 120,
    totalUnusedVouchers: 60,
    pendingCommission: 800,
    paidCommission: 600,
  },
  {
    id: 6,
    imgs: 'fa fa-rocket',
    companyTitle: 'Company F',
    totalVouchers: 250,
    totalUsedVouchers: 200,
    totalUnusedVouchers: 50,
    pendingCommission: 1000,
    paidCommission: 800,
  },
];
